### ISSUE TITLE
gethostbyname returns -95

### ISSUE THREAD

**Issue by steveww** [wadetb/tinyhci#2]
When calling gethostbyname it returns an error code of -95.

The device has been initialised and has an IP address assigned. Has DNS been set up by DHCP?

**Comment by Sweet-Peas** [comment]
Sounds great @steveww I'm also looking forward to seeing you progress.

**Comment by steveww** [comment]
Ready to post my changes. However I have changed quite a lot. I could commit to this repo or create one of my own and you merge in what you want. ????

**Comment by wadetb** [comment]
I'm no Git expert, but you typically fork the tinyhci repository on GitHub, clone your fork to your PC, replace the files, push the changed / replaced files to your fork, and then send me a pull request.  Then I'll figure out what to do with getting them into the "official" repo.

**Comment by steveww** [comment]
I am still very new to Git and still getting the hang of it. Just figuring out how to work with it. I have created my own clone repository under my own space with the new code. I don't think this approach is correct. I will try again.
